"""Pydantic schemas for API request/response validation."""
from app.schemas.company import (
    CompanyBase,
    CompanyCreate,
    CompanyUpdate,
    CompanyInDB,
    Company,
    CompanyWithFilingsCount,
)
from app.schemas.filing import (
    FilingDocumentBase,
    FilingDocumentCreate,
    FilingDocumentInDB,
    FilingDocument,
    FilingBase,
    FilingCreate,
    FilingUpdate,
    FilingInDB,
    Filing,
    FilingWithCompany,
    FilingWithDocuments,
    FilingDetail,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    User,
    UserProfile,
)
from app.schemas.alert import (
    UserAlertBase,
    UserAlertCreate,
    UserAlertUpdate,
    UserAlertInDB,
    UserAlert,
    UserAlertWithMatches,
    AlertMatchBase,
    AlertMatchCreate,
    AlertMatchUpdate,
    AlertMatchInDB,
    AlertMatch,
    AlertMatchWithDetails,
)

__all__ = [
    # Company schemas
    "CompanyBase",
    "CompanyCreate",
    "CompanyUpdate",
    "CompanyInDB",
    "Company",
    "CompanyWithFilingsCount",
    # Filing schemas
    "FilingDocumentBase",
    "FilingDocumentCreate",
    "FilingDocumentInDB",
    "FilingDocument",
    "FilingBase",
    "FilingCreate",
    "FilingUpdate",
    "FilingInDB",
    "Filing",
    "FilingWithCompany",
    "FilingWithDocuments",
    "FilingDetail",
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "User",
    "UserProfile",
    # Alert schemas
    "UserAlertBase",
    "UserAlertCreate",
    "UserAlertUpdate",
    "UserAlertInDB",
    "UserAlert",
    "UserAlertWithMatches",
    "AlertMatchBase",
    "AlertMatchCreate",
    "AlertMatchUpdate",
    "AlertMatchInDB",
    "AlertMatch",
    "AlertMatchWithDetails",
]
